### ISSUE TITLE
Struktur för projeket.

### ISSUE THREAD

**Issue by emilpriver** [littlekid/itingrid#9]
För att göra det enklare för utvecklare att utveckla projektet borde en bättre struktur för alla filer finnas. Istället för att skriva CSS i var html fil är en rekomendation o fördela upp projektet i undermappar. Genom o fördela filerna är de enklare o återanvända kod med.

Exempelvis:
för alla assets:
- assets/css
- assets/img
- assets/script

**Comment by littlekid** [comment]
Har städat upp i root-mappen och flyttat "diverse" till en wip-work-in-progress-mapp. Just nu finns bara dessa filer:
* README 
* index.html
* design.css

Jag är för att skapa mappar för att strukturera upp innehållet så småningom när det behövs. Just nu får dessa tre ligga direkt i root. Lättare att se allt som finns direkt på ett ställe när det är så få filer. :]
